version: "3.8"
services:
  wp:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - wp_data:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  wp_data:
  mysql_data: